sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - hexo # build hexo branch only
script:
  - sed -i "s/SecretId/${SecretId}/" _config.yml
  - sed -i "s/SecretKey/${SecretKey}/" _config.yml
  - hexo generate # generate static files
  - hexo deploy # deploy static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target_branch: master
  on:
    branch: hexo
  local-dir: public