name: CI
on:
  push:
    branches:
      - hexo-5
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout              # 拉取当前执行 Actions 仓库的指定分支
        uses: actions/checkout@v2
        with:
          ref: hexo-5
      - name: Setup Node            # 安装 Node 环境
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Setup hexo
        env:
          GIT_NAME: ${{ secrets.GIT_NAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "$GIT_NAME"
          git config --global user.email "$GIT_EMAIL"
          npm install hexo-cli -g
          npm install
      - name: Hexo build
        run: |
          hexo clean
          hexo generate
          hexo deploy
      - name: Deploy to COS
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
        uses: fajiaopaopao/tencent-cos-action@v0.2.0
        with:
          args: delete -r -f / && upload -r ./public/ /
          secret_id: ${{ secrets.SECRET_ID }}
          secret_key: ${{ secrets.SECRET_KEY }}
          bucket: ${{ secrets.BUCKET }}
          region: ap-beijing
  
